import Footer from '@/components/Footer'
import MainContainer from '@/components/MainContainer'
import NavigationBar from '@/components/NavigationBar'
import Head from 'next/head'

const Home: React.FC = () => {


  return (
    <>
      <Head>
        <title>MKS Sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
      <MainContainer />
      <Footer />
      </>
  )
}

export default Home